// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkG0SbY5Yr9DMcOLDlcdp-6q8OITdGA2A',
    appId: '1:461638369659:web:1dfa99f968bab25c2a3dde',
    messagingSenderId: '461638369659',
    projectId: 'meau-app-2022',
    authDomain: 'meau-app-2022.firebaseapp.com',
    storageBucket: 'meau-app-2022.appspot.com',
    measurementId: 'G-444PBTFN89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbvHCVMAz915Z4TA-79FEZ_enJ1XSRro',
    appId: '1:461638369659:android:963cfcda48aef7cb2a3dde',
    messagingSenderId: '461638369659',
    projectId: 'meau-app-2022',
    storageBucket: 'meau-app-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvzychD03fZiwPYAdlv8Kt7ucBMZd76A',
    appId: '1:461638369659:ios:02f8a9bf074a76412a3dde',
    messagingSenderId: '461638369659',
    projectId: 'meau-app-2022',
    storageBucket: 'meau-app-2022.appspot.com',
    iosClientId: '461638369659-lnsbjobovop7camuoqnu20gtodp29hkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.meau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvzychD03fZiwPYAdlv8Kt7ucBMZd76A',
    appId: '1:461638369659:ios:02f8a9bf074a76412a3dde',
    messagingSenderId: '461638369659',
    projectId: 'meau-app-2022',
    storageBucket: 'meau-app-2022.appspot.com',
    iosClientId: '461638369659-lnsbjobovop7camuoqnu20gtodp29hkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.meau',
  );
}
